version: '3'

services:

  worker:
    build: .
    ports:
      - "8081:8081"
      - "5000:5000"

    command: runner worker master

  master:
    build: .
    ports:
      - "8080:8080"
      - "7077:7077"
      - "6066:6066"

    command: runner master

  shell:
    build: .
    ports:
      - "4040:4040"

    command: runner shell

  proxy:
    build:
      context: .
      dockerfile: proxy/Dockerfile.proxy
    ports:
      - "80:80"
